export const LEARNING_TIME_HEARTBEAT_INTERVAL_MS = 15_000;
export const LEARNING_TIME_MIN_INTERVAL_MS = 8_000;
export const LEARNING_TIME_MAX_INTERVAL_MS = 30_000;
export const LEARNING_TIME_MAX_CREDIT_SECONDS = 20;
export const LEARNING_TIME_MAX_SESSION_SECONDS = 86_400;

