import {
  Award,
  BookOpen,
  Bookmark,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  CircleHelp,
  ClipboardCheck,
  FileText,
  Globe2,
  GraduationCap,
  Heart,
  Home,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  Link2,
  Mail,
  MapPin,
  Megaphone,
  MessagesSquare,
  Phone,
  Rocket,
  ShieldCheck,
  ShoppingBag,
  Star,
  Target,
  Trophy,
  UserRound,
  UsersRound,
  Video,
} from "lucide-react";
import type { MemberSidebarLinkIcon } from "@/lib/member-sidebar-link-model";

export const memberSidebarLinkIconComponents = {
  link: Link2,
  "book-open": BookOpen,
  "life-buoy": LifeBuoy,
  video: Video,
  "file-text": FileText,
  globe: Globe2,
  "messages-square": MessagesSquare,
  calendar: CalendarDays,
  home: Home,
  "graduation-cap": GraduationCap,
  library: LibraryBig,
  bookmark: Bookmark,
  award: Award,
  trophy: Trophy,
  users: UsersRound,
  "user-round": UserRound,
  briefcase: BriefcaseBusiness,
  building: Building2,
  chart: ChartNoAxesCombined,
  "clipboard-check": ClipboardCheck,
  "circle-help": CircleHelp,
  lightbulb: Lightbulb,
  megaphone: Megaphone,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  rocket: Rocket,
  star: Star,
  target: Target,
  heart: Heart,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
} as const satisfies Record<MemberSidebarLinkIcon, typeof Link2>;
