import type { AppLocale } from "@/lib/i18n/model";

const de = {
  page: { metadataTitle: "Integrationen", eyebrow: "System", title: "Integrationen", description: "Verkaufsprovider, Produktzugriffe, Automationen und Supportkanal." },
  common: { active: "Aktiv", activate: "Aktivieren", deactivate: "Deaktivieren", save: "Speichern", create: "Anlegen", connect: "Verbinden" },
  stats: { aria: "Commerce-Status", orders: "Bestellungen", subscriptions: "Abonnements", entitlements: "Aktive Zugriffe", failedEvents: "Fehlerhafte Events" },
  connection: { sectionTitle: "Verkaufsprovider", connectProvider: "Provider verbinden", provider: "Provider", displayName: "Anzeigename", signatureMode: "Signaturmodus", hmac: "HMAC-SHA256 über Raw Body", digistore: "Digistore SHA-512 Feldkanonisierung", token: "Shared-Token-Header", secret: "Signaturgeheimnis", unchanged: "Unverändert lassen", minimum: "Mindestens 16 Zeichen", inviteMembers: "Mitglieder automatisch einladen", copyEndpoint: "Endpoint kopieren" },
  product: { title: "Verkaufsprodukt", name: "Produktname", sku: "SKU", selectBundle: "Bundle wählen" },
  mapping: { title: "Produktzuordnung", selectProvider: "Provider wählen", selectProduct: "Produkt wählen", providerProductId: "Provider-Produkt-ID", variant: "Variante (optional)", submit: "Zuordnen" },
  workflow: { title: "n8n-Workflows", name: "Workflow-Name", secret: "HMAC-Signaturgeheimnis", events: "Events", orderCreated: "Bestellung erstellt", subscriptionActivated: "Abonnement aktiviert", paymentFailed: "Zahlung fehlgeschlagen", subscriptionCancelled: "Abonnement gekündigt", subscriptionExpired: "Abonnement abgelaufen", entitlementGranted: "Zugriff gewährt", entitlementRevoked: "Zugriff entzogen", memberUpserted: "Mitglied aktualisiert", n8nTriggered: "n8n ausgelöst" },
  support: { title: "Supportkanal", channel: "Kanal", link: "Support-Link", email: "E-Mail", launcher: "Launcher-Text", appId: "Intercom App-ID", secretUnchanged: "Identity-Secret unverändert", secret: "Intercom Identity-Secret", removeSecret: "Identity-Secret entfernen" },
  messages: { invalid: "Bitte prüfe die Eingaben.", connectionSecretShort: "Das Signaturgeheimnis muss mindestens 16 Zeichen enthalten.", connectionCreated: "Verbindung angelegt.", connectionUpdated: "Verbindung aktualisiert.", connectionFailed: "Die Providerverbindung konnte nicht gespeichert werden.", bundleMissing: "Das Bundle wurde nicht gefunden oder ist inaktiv.", productCreated: "Verkaufsprodukt angelegt.", productFailed: "Produkt oder SKU existiert bereits.", mappingTargetMissing: "Verbindung oder Produkt wurde nicht gefunden.", mappingCreated: "Produktzuordnung angelegt.", mappingFailed: "Diese Providerzuordnung existiert bereits.", supportSecretMissing: "Für verifizierte Intercom-Identitäten fehlt das Identity-Secret.", supportSaved: "Supportkanal gespeichert.", workflowCreated: "n8n-Workflow verbunden.", workflowFailed: "Der n8n-Workflow konnte nicht verbunden werden." },
};
type WidenCopy<T> = T extends (...args: infer Args) => string ? (...args: Args) => string : T extends string ? string : { readonly [Key in keyof T]: WidenCopy<T[Key]> };
export type IntegrationAdminCopy = WidenCopy<typeof de>;

const en: IntegrationAdminCopy = {
  page: { metadataTitle: "Integrations", eyebrow: "System", title: "Integrations", description: "Sales providers, product access, automations and support channel." },
  common: { active: "Active", activate: "Activate", deactivate: "Deactivate", save: "Save", create: "Create", connect: "Connect" },
  stats: { aria: "Commerce status", orders: "Orders", subscriptions: "Subscriptions", entitlements: "Active access", failedEvents: "Failed events" },
  connection: { sectionTitle: "Sales providers", connectProvider: "Connect provider", provider: "Provider", displayName: "Display name", signatureMode: "Signature mode", hmac: "HMAC-SHA256 over raw body", digistore: "Digistore SHA-512 field canonicalization", token: "Shared token header", secret: "Signature secret", unchanged: "Leave unchanged", minimum: "At least 16 characters", inviteMembers: "Invite members automatically", copyEndpoint: "Copy endpoint" },
  product: { title: "Sales product", name: "Product name", sku: "SKU", selectBundle: "Select bundle" },
  mapping: { title: "Product mapping", selectProvider: "Select provider", selectProduct: "Select product", providerProductId: "Provider product ID", variant: "Variant (optional)", submit: "Map" },
  workflow: { title: "n8n workflows", name: "Workflow name", secret: "HMAC signature secret", events: "Events", orderCreated: "Order created", subscriptionActivated: "Subscription activated", paymentFailed: "Payment failed", subscriptionCancelled: "Subscription cancelled", subscriptionExpired: "Subscription expired", entitlementGranted: "Access granted", entitlementRevoked: "Access revoked", memberUpserted: "Member updated", n8nTriggered: "n8n triggered" },
  support: { title: "Support channel", channel: "Channel", link: "Support link", email: "Email", launcher: "Launcher label", appId: "Intercom app ID", secretUnchanged: "Leave identity secret unchanged", secret: "Intercom identity secret", removeSecret: "Remove identity secret" },
  messages: { invalid: "Check the input.", connectionSecretShort: "The signature secret must contain at least 16 characters.", connectionCreated: "Connection created.", connectionUpdated: "Connection updated.", connectionFailed: "The provider connection could not be saved.", bundleMissing: "The bundle was not found or is inactive.", productCreated: "Sales product created.", productFailed: "The product or SKU already exists.", mappingTargetMissing: "The connection or product was not found.", mappingCreated: "Product mapping created.", mappingFailed: "This provider mapping already exists.", supportSecretMissing: "Verified Intercom identities require an identity secret.", supportSaved: "Support channel saved.", workflowCreated: "n8n workflow connected.", workflowFailed: "The n8n workflow could not be connected." },
};

const it: IntegrationAdminCopy = {
  page: { metadataTitle: "Integrazioni", eyebrow: "Sistema", title: "Integrazioni", description: "Provider di vendita, accessi ai prodotti, automazioni e canale di supporto." },
  common: { active: "Attivo", activate: "Attiva", deactivate: "Disattiva", save: "Salva", create: "Crea", connect: "Collega" },
  stats: { aria: "Stato commerce", orders: "Ordini", subscriptions: "Abbonamenti", entitlements: "Accessi attivi", failedEvents: "Eventi non riusciti" },
  connection: { sectionTitle: "Provider di vendita", connectProvider: "Collega provider", provider: "Provider", displayName: "Nome visualizzato", signatureMode: "Modalità firma", hmac: "HMAC-SHA256 sul corpo raw", digistore: "Canonizzazione campi Digistore SHA-512", token: "Header token condiviso", secret: "Segreto di firma", unchanged: "Lascia invariato", minimum: "Almeno 16 caratteri", inviteMembers: "Invita automaticamente i membri", copyEndpoint: "Copia endpoint" },
  product: { title: "Prodotto di vendita", name: "Nome prodotto", sku: "SKU", selectBundle: "Seleziona bundle" },
  mapping: { title: "Mappatura prodotto", selectProvider: "Seleziona provider", selectProduct: "Seleziona prodotto", providerProductId: "ID prodotto provider", variant: "Variante (facoltativa)", submit: "Mappa" },
  workflow: { title: "Workflow n8n", name: "Nome workflow", secret: "Segreto firma HMAC", events: "Eventi", orderCreated: "Ordine creato", subscriptionActivated: "Abbonamento attivato", paymentFailed: "Pagamento non riuscito", subscriptionCancelled: "Abbonamento annullato", subscriptionExpired: "Abbonamento scaduto", entitlementGranted: "Accesso concesso", entitlementRevoked: "Accesso revocato", memberUpserted: "Membro aggiornato", n8nTriggered: "n8n attivato" },
  support: { title: "Canale di supporto", channel: "Canale", link: "Link supporto", email: "E-mail", launcher: "Testo launcher", appId: "ID app Intercom", secretUnchanged: "Lascia invariato il segreto identità", secret: "Segreto identità Intercom", removeSecret: "Rimuovi segreto identità" },
  messages: { invalid: "Controlla i dati inseriti.", connectionSecretShort: "Il segreto di firma deve contenere almeno 16 caratteri.", connectionCreated: "Connessione creata.", connectionUpdated: "Connessione aggiornata.", connectionFailed: "Non è stato possibile salvare la connessione del provider.", bundleMissing: "Il bundle non è stato trovato o non è attivo.", productCreated: "Prodotto di vendita creato.", productFailed: "Il prodotto o SKU esiste già.", mappingTargetMissing: "La connessione o il prodotto non è stato trovato.", mappingCreated: "Mappatura prodotto creata.", mappingFailed: "Questa mappatura provider esiste già.", supportSecretMissing: "Le identità Intercom verificate richiedono un segreto identità.", supportSaved: "Canale di supporto salvato.", workflowCreated: "Workflow n8n collegato.", workflowFailed: "Non è stato possibile collegare il workflow n8n." },
};

const es: IntegrationAdminCopy = {
  page: { metadataTitle: "Integraciones", eyebrow: "Sistema", title: "Integraciones", description: "Proveedores de ventas, accesos a productos, automatizaciones y canal de soporte." },
  common: { active: "Activo", activate: "Activar", deactivate: "Desactivar", save: "Guardar", create: "Crear", connect: "Conectar" },
  stats: { aria: "Estado de comercio", orders: "Pedidos", subscriptions: "Suscripciones", entitlements: "Accesos activos", failedEvents: "Eventos fallidos" },
  connection: { sectionTitle: "Proveedores de ventas", connectProvider: "Conectar proveedor", provider: "Proveedor", displayName: "Nombre visible", signatureMode: "Modo de firma", hmac: "HMAC-SHA256 sobre cuerpo raw", digistore: "Canonización de campos Digistore SHA-512", token: "Cabecera de token compartido", secret: "Secreto de firma", unchanged: "Dejar sin cambios", minimum: "Al menos 16 caracteres", inviteMembers: "Invitar miembros automáticamente", copyEndpoint: "Copiar endpoint" },
  product: { title: "Producto de venta", name: "Nombre del producto", sku: "SKU", selectBundle: "Seleccionar paquete" },
  mapping: { title: "Asignación de producto", selectProvider: "Seleccionar proveedor", selectProduct: "Seleccionar producto", providerProductId: "ID de producto del proveedor", variant: "Variante (opcional)", submit: "Asignar" },
  workflow: { title: "Flujos n8n", name: "Nombre del flujo", secret: "Secreto de firma HMAC", events: "Eventos", orderCreated: "Pedido creado", subscriptionActivated: "Suscripción activada", paymentFailed: "Pago fallido", subscriptionCancelled: "Suscripción cancelada", subscriptionExpired: "Suscripción caducada", entitlementGranted: "Acceso concedido", entitlementRevoked: "Acceso revocado", memberUpserted: "Miembro actualizado", n8nTriggered: "n8n activado" },
  support: { title: "Canal de soporte", channel: "Canal", link: "Enlace de soporte", email: "Correo electrónico", launcher: "Texto del lanzador", appId: "ID de app Intercom", secretUnchanged: "Dejar secreto de identidad sin cambios", secret: "Secreto de identidad Intercom", removeSecret: "Eliminar secreto de identidad" },
  messages: { invalid: "Comprueba los datos.", connectionSecretShort: "El secreto de firma debe contener al menos 16 caracteres.", connectionCreated: "Conexión creada.", connectionUpdated: "Conexión actualizada.", connectionFailed: "No se pudo guardar la conexión del proveedor.", bundleMissing: "No se encontró el paquete o está inactivo.", productCreated: "Producto de venta creado.", productFailed: "El producto o SKU ya existe.", mappingTargetMissing: "No se encontró la conexión o el producto.", mappingCreated: "Asignación de producto creada.", mappingFailed: "Esta asignación de proveedor ya existe.", supportSecretMissing: "Las identidades Intercom verificadas requieren un secreto de identidad.", supportSaved: "Canal de soporte guardado.", workflowCreated: "Flujo n8n conectado.", workflowFailed: "No se pudo conectar el flujo n8n." },
};

const fr: IntegrationAdminCopy = {
  page: { metadataTitle: "Intégrations", eyebrow: "Système", title: "Intégrations", description: "Fournisseurs de vente, accès aux produits, automatisations et canal d'assistance." },
  common: { active: "Actif", activate: "Activer", deactivate: "Désactiver", save: "Enregistrer", create: "Créer", connect: "Connecter" },
  stats: { aria: "État du commerce", orders: "Commandes", subscriptions: "Abonnements", entitlements: "Accès actifs", failedEvents: "Événements en échec" },
  connection: { sectionTitle: "Fournisseurs de vente", connectProvider: "Connecter un fournisseur", provider: "Fournisseur", displayName: "Nom affiché", signatureMode: "Mode de signature", hmac: "HMAC-SHA256 sur le corps brut", digistore: "Canonisation des champs Digistore SHA-512", token: "En-tête de jeton partagé", secret: "Secret de signature", unchanged: "Laisser inchangé", minimum: "Au moins 16 caractères", inviteMembers: "Inviter automatiquement les membres", copyEndpoint: "Copier l'endpoint" },
  product: { title: "Produit de vente", name: "Nom du produit", sku: "SKU", selectBundle: "Sélectionner une offre" },
  mapping: { title: "Correspondance produit", selectProvider: "Sélectionner un fournisseur", selectProduct: "Sélectionner un produit", providerProductId: "ID produit fournisseur", variant: "Variante (facultative)", submit: "Associer" },
  workflow: { title: "Workflows n8n", name: "Nom du workflow", secret: "Secret de signature HMAC", events: "Événements", orderCreated: "Commande créée", subscriptionActivated: "Abonnement activé", paymentFailed: "Paiement échoué", subscriptionCancelled: "Abonnement annulé", subscriptionExpired: "Abonnement expiré", entitlementGranted: "Accès accordé", entitlementRevoked: "Accès retiré", memberUpserted: "Membre mis à jour", n8nTriggered: "n8n déclenché" },
  support: { title: "Canal d'assistance", channel: "Canal", link: "Lien d'assistance", email: "E-mail", launcher: "Texte du lanceur", appId: "ID d'app Intercom", secretUnchanged: "Laisser le secret d'identité inchangé", secret: "Secret d'identité Intercom", removeSecret: "Supprimer le secret d'identité" },
  messages: { invalid: "Vérifiez les informations saisies.", connectionSecretShort: "Le secret de signature doit contenir au moins 16 caractères.", connectionCreated: "Connexion créée.", connectionUpdated: "Connexion mise à jour.", connectionFailed: "La connexion du fournisseur n'a pas pu être enregistrée.", bundleMissing: "L'offre est introuvable ou inactive.", productCreated: "Produit de vente créé.", productFailed: "Le produit ou le SKU existe déjà.", mappingTargetMissing: "La connexion ou le produit est introuvable.", mappingCreated: "Correspondance produit créée.", mappingFailed: "Cette correspondance fournisseur existe déjà.", supportSecretMissing: "Les identités Intercom vérifiées nécessitent un secret d'identité.", supportSaved: "Canal d'assistance enregistré.", workflowCreated: "Workflow n8n connecté.", workflowFailed: "Le workflow n8n n'a pas pu être connecté." },
};

const dictionaries = { de, en, it, es, fr } satisfies Record<AppLocale, IntegrationAdminCopy>;
export function getIntegrationAdminCopy(locale: AppLocale) { return dictionaries[locale]; }
export { dictionaries as integrationAdminDictionaries };
